alias cdsga='cd ~/ddsunl/sga/sgacode/sga-privado/sga/'
alias cdsgatest='cd ~/ddsunl/sga/sgacode/sga-privado-test/sga/'
alias envsga='source ~/ddsunl/sga/sgaenv/bin/activate'
alias shsga='envsga; cdsga; tg-admin shell'
alias runsga='envsga;cdsga; python start-sga-privado.py'
alias runsgatest='envsga;cdsgatest; python start-sga-privado.py'